In [ ]:
import numpy as np
#RANDOM M0DULE IS SUB-PACKAGE OF NUMPY

In [ ]:
a=np.random.rand(1)
print(a)

[0.63669086]


In [ ]:
C = np.random.rand(8,4)  #rand-range is between 0 and 1
print(C)

[[0.30076888 0.77955218 0.7587343  0.79530862]
 [0.02084284 0.08582214 0.42815524 0.33596581]
 [0.6644152  0.52993929 0.20135833 0.4985694 ]
 [0.25892631 0.83620535 0.98174996 0.27773965]
 [0.88634062 0.31036971 0.17114165 0.62470629]
 [0.85071222 0.91420892 0.32044298 0.68905124]
 [0.46242883 0.51018195 0.68794698 0.65164007]
 [0.05582132 0.7656205  0.34349165 0.1517082 ]]


In [ ]:
A=np.arange(32).reshape(8,4)
print(A)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


In [ ]:
a= 10*np.random.rand(8,4)  #rand-range is between 0 and 1
print(a)

[[2.88520202 1.40974725 8.25958436 9.64959622]
 [3.4923978  1.01713503 2.9566536  3.55564295]
 [3.11772346 2.69392814 5.29181576 1.23541954]
 [0.76961687 8.33985154 5.83585206 2.56139962]
 [1.18836496 8.73286814 9.58192128 3.92494843]
 [4.26320416 6.27923758 0.99769462 4.85899424]
 [7.62281972 5.18920937 1.81300556 4.93524094]
 [7.64141321 4.12778457 5.0667165  0.78258724]]


In [ ]:
B= np.floor(10*np.random.rand(8,4) ) #rand-range is between 0 and 1
print(B)

[[9. 8. 0. 6.]
 [7. 0. 0. 2.]
 [6. 4. 1. 9.]
 [7. 3. 7. 6.]
 [3. 8. 3. 0.]
 [9. 7. 3. 7.]
 [3. 8. 8. 3.]
 [3. 6. 4. 6.]]


In [ ]:
np.vsplit(A,4)

[array([[9., 8., 0., 6.],
        [7., 0., 0., 2.]]),
 array([[6., 4., 1., 9.],
        [7., 3., 7., 6.]]),
 array([[3., 8., 3., 0.],
        [9., 7., 3., 7.]]),
 array([[3., 8., 8., 3.],
        [3., 6., 4., 6.]])]

In [ ]:
np.vsplit(A,3)

ValueError: array split does not result in an equal division

In [ ]:
np.vsplit(A,(2,7))    #split it after second row and seventh row

[array([[9., 8., 0., 6.],
        [7., 0., 0., 2.]]),
 array([[6., 4., 1., 9.],
        [7., 3., 7., 6.],
        [3., 8., 3., 0.],
        [9., 7., 3., 7.],
        [3., 8., 8., 3.]]),
 array([[3., 6., 4., 6.]])]

In [ ]:
H=np.arange(32).reshape(4,8)
print(H)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]]


In [ ]:
np.vsplit(H,4)

[array([[0, 1, 2, 3, 4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11, 12, 13, 14, 15]]),
 array([[16, 17, 18, 19, 20, 21, 22, 23]]),
 array([[24, 25, 26, 27, 28, 29, 30, 31]])]

In [ ]:
np.hsplit(H,4)

[array([[ 0,  1],
        [ 8,  9],
        [16, 17],
        [24, 25]]),
 array([[ 2,  3],
        [10, 11],
        [18, 19],
        [26, 27]]),
 array([[ 4,  5],
        [12, 13],
        [20, 21],
        [28, 29]]),
 array([[ 6,  7],
        [14, 15],
        [22, 23],
        [30, 31]])]

In [ ]:
np.hsplit(H,(3,7))

[array([[ 0,  1,  2],
        [ 8,  9, 10],
        [16, 17, 18],
        [24, 25, 26]]),
 array([[ 3,  4,  5,  6],
        [11, 12, 13, 14],
        [19, 20, 21, 22],
        [27, 28, 29, 30]]),
 array([[ 7],
        [15],
        [23],
        [31]])]

In [ ]:
np.hsplit(H,(2,5))

[array([[ 0,  1],
        [ 8,  9],
        [16, 17],
        [24, 25]]),
 array([[ 2,  3,  4],
        [10, 11, 12],
        [18, 19, 20],
        [26, 27, 28]]),
 array([[ 5,  6,  7],
        [13, 14, 15],
        [21, 22, 23],
        [29, 30, 31]])]

Trigonometry

In [ ]:
np.pi

3.141592653589793

In [ ]:
A = [np.pi/4,np.pi/3,np.pi/2,np.pi]
print(A)

[0.7853981633974483, 1.0471975511965976, 1.5707963267948966, 3.141592653589793]


In [ ]:
np.rad2deg(A)    #convert radians to degrees

array([ 45.,  60.,  90., 180.])

In [ ]:
np.deg2rad(A)   #convert degrees to radians

array([0.01370778, 0.01827705, 0.02741557, 0.05483114])

In [ ]:
B=np.deg2rad(A)

In [ ]:
np.sin(1)    #radians

0.8414709848078965

In [ ]:
np.cos(1)

0.5403023058681398

In [ ]:
np.tan(1)

1.5574077246549023

Statistics

In [ ]:
st = np.array([23,45,67,89,21,34])

In [ ]:
np.mean(st)    #(sum of products/no of products)

46.5

In [ ]:
np.median(st)   #Average value

39.5

In [ ]:
np.std(st)   #standard deviation

24.452334585202017

In [ ]:
np.var(st)   #(standard deviation)^2=variance

597.9166666666666

In [ ]:
c = np.arange(1,5).reshape(2,2)
print(c)

[[1 2]
 [3 4]]


In [ ]:
np.linalg.inv(c)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [ ]:
C = np.arange(1,25).reshape(6,4)
print(C)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


In [ ]:
print(np.argmax(C))

23


In [ ]:
C = 10*np.random.rand(24).reshape(6,4)
print(C)

[[9.08280951 7.94201155 5.83917101 5.2695283 ]
 [1.40864149 4.81752279 5.10196535 6.99612961]
 [7.85925062 4.35649604 8.96573942 6.44928938]
 [2.98679896 0.63120571 9.69553038 6.79488672]
 [4.21943602 8.1780225  8.83577454 8.25417939]
 [9.33097312 3.25992532 9.83213492 2.27201873]]


In [ ]:
print(np.argmax(C))

22


In [ ]:
print(np.argmax(C,axis=1))    #row wise maximum

[0 3 2 2 2 2]


In [ ]:
print(np.argmax(C,axis=0))    #column wise maximum

[5 4 5 4]


In [ ]:
print(np.argmin(C))

13


In [ ]:
print(np.argmin(C,axis=0))

[1 3 1 5]


In [ ]:
print(np.argmin(C,axis=1))

[3 0 1 1 0 3]


Searching

In [ ]:
a = np.array([34,56,17,7,88,91])
print(np.where(a%2==0))

(array([0, 1, 4]),)


In [ ]:
a = np.array([34,56,17,7,88,91])
print(np.where(a%2==1))

(array([2, 3, 5]),)


In [ ]:
s = np.array([24,16,7,17,54,60])
print(np.where (s%6==0))

(array([0, 4, 5]),)


In [ ]:
S = np.array([7,10,25,66,90])
x = np.searchsorted(S,10)
print(x)

1


In [ ]:
S = np.array([7,10,5,6,90])
x = np.searchsorted(S,10)
print(x)

4


In [ ]:
a = np.array(['babu','ajay','ramana'])
print(np.sort(a))

['ajay' 'babu' 'ramana']


In [ ]:
a = np.array([True,False,True])
print(np.sort(a))

[False  True  True]


In [ ]:
a = np.array([[3,2,4],[5,0,1]])
print(np.sort(a))

[[2 3 4]
 [0 1 5]]


In [ ]:
arr = np.array([40,43,50,44,67,78])
filt=np.where(arr%2==0)
print(filt)

(array([0, 2, 3, 5]),)


In [ ]:
arr[filt]

array([40, 50, 44, 78])

Iterating through two Arrays

In [ ]:
names = np.array(["hemanth","abdul","revanth","manohar","vinay"])
initials = np.array(["k","M","s","T","D"])
for i,j in zip(initials,names):
  print(i,".",j)

k . hemanth
M . abdul
s . revanth
T . manohar
D . vinay


In [ ]:
names = np.array(["hemanth","abdul","revanth","manohar","vinay"])
initials = np.array(["k","M","s","T","D"])
age = np.array([20,19,22,21,25])
for i,j,k in zip(initials,names,age):
  print(i,".",j,".",k)

k . hemanth . 20
M . abdul . 19
s . revanth . 22
T . manohar . 21
D . vinay . 25


In [ ]:
a1 = np.array([34,56,7,17,88,91])
a2 = np.array([24,16,7,17,54,60])
n=np.multiply(a1,a2)

[ 816  896   49  289 4752 5460]


In [ ]:
a1 = np.array([34,56,7,17,88,91])
a2 = np.array([24,16,7,17,54,60])
n=np.divide(a1,a2)
print(n)

[1.41666667 3.5        1.         1.         1.62962963 1.51666667]


In [ ]:
a1 = np.array([34,56,7,17,88,91])
a2 = np.array([24,16,7,17,54,60])
n=np.mod(a1,a2)
print(n)

[10  8  0  0 34 31]


In [ ]:
a1 = np.array([34,56,7,17,88,91])
a2 = np.array([24,16,7,17,54,60])
n=np.divmod(a1,a2)
print(n)

(array([1, 3, 1, 1, 1, 1]), array([10,  8,  0,  0, 34, 31]))


Logarithms

In [ ]:
a1 = np.arange(1,10)     #log base 2
print(a1)
print(np.log2(a1))

[1 2 3 4 5 6 7 8 9]
[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]


In [ ]:
a=1.2
print(np.log(a))    #Natural log e

0.1823215567939546


In [ ]:
a=1.2                  #log base 10
print(np.log10(a))

0.07918124604762482


Other Mathematical Functions

In [ ]:
a2 = np.array([5,6,7,10])
x=np.cumprod(a2)
print(x)

[   5   30  210 2100]


In [ ]:
a2 = np.array([5,6,7,10])
x=np.cumsum(a2)
print(x)

[ 5 11 18 28]


In [ ]:
a2 = np.array([5,6,7,10])
x=np.diff(a2)
print(x)

[1 1 3]


In [ ]:
num1 = 455
num2 = 665
x = np.lcm(num1,num2)
print(x)

8645


In [ ]:
num1 = 455
num2 = 665
x = np.gcd(num1,num2)
print(x)

35


In [ ]:
 a= np.array([12,15,45,60])
gc = np.gcd.reduce(a)
print(gc)

3


In [ ]:
 a= np.array([12,15,45,60])
gc = np.lcm.reduce(a)
print(gc)

180
